### ISSUE TITLE
Design & Security concerns

### ISSUE THREAD

**Issue by bennetgallein** [WrightProjects/TS3AudioBot-Dashboard-NQ#5]
Hey, I only quickly jumped through the code looking for the way you communicate with the Bot.

Quickly I found things similar to the follow: https://github.com/WrightProjects/TS3AudioBot-Dashboard-NQ/blob/0e41c03dd3c4cca0d2bca318a3c2c4319f2ad4ab/application/controllers/api/Bot.php#L127 

or

https://github.com/WrightProjects/TS3AudioBot-Dashboard-NQ/blob/0e41c03dd3c4cca0d2bca318a3c2c4319f2ad4ab/application/controllers/api/Bot.php#L147

I really do not recommend using those PHP functions since they are a direct intepretation of user input. Also TS3AudioBot itself offers a native WebAPI which would not be hard to implement for you in your current setup, even more easier if you use the wrapper which is on my profile!

**Comment by WrightBlue** [comment]
Hi, This version of the interface is for the old version of ts3audiobot. Interface [premium](https://tsforum.pl/temat/5341-ts3ab-panel-vip-informacje/) version uses webapi ;)
